[package]
name = "htmx"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/studeo14/clisp-web"

[dependencies]
rocket = "0.5.*"
rand = "*"

[dependencies.rocket_dyn_templates]
version = "0.2.*"
features = ["handlebars", "tera", "minijinja"]

